### ISSUE TITLE
Why is stack reset at 0x10FD?

### ISSUE THREAD

**Issue by yunxing** [bugzmanov/nes_ebook#10]
Hi... looking at the code https://github.com/bugzmanov/nes_ebook/blob/master/code/ch8/src/cpu.rs#L31 I wonder why the stack is reset at 0x10FD, shouldn't it start at 0x10FF according to the spec?

**Comment by bugzmanov** [comment]
Hey @yunxing . Thanks for reading! :)
Good question. This nesdev forum might bring some light: https://forums.nesdev.com/viewtopic.php?f=3&t=19858.
So I believe the proper way would be to start 0x10FF and they to execute reset interrupt that will put zeros to 0x10FF and 0x10FE, but looks like I took a shortcut and just start stack from 0x10FD. 

If you'll create a PR that clarifies this POINT in the chapter on interrupts, I would be very grateful :)

**Comment by yunxing** [comment]
Thanks for replying! 

> If you'll create a PR that clarifies this POINT in the chapter on interrupts
Guess I will have to read that chapter first :)
