### ISSUE TITLE
SDL2 link error and fix. (Os win10)

### ISSUE THREAD

**Issue by 123zmz123** [bugzmanov/nes_ebook#11]
To compile SDL2,  seems like we need more configutration on windows. for me , I use windows 10,  
at command line I will type
![image](https://user-images.githubusercontent.com/16858675/116237125-6bc3f400-a792-11eb-8609-29a8fd510269.png)
it means I need download msvc version of sdl2 at here http://www.libsdl.org/release/SDL2-2.0.14-win32-x64.zip
unzip the file 

copy ./SDL2-2.014/lib/x64/SDL2.lib .. SDL2main.lib .. SDL2test.lib to 
C:\Users\Your_user_name\ .rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib\

copy ./SDL2-2.014/lib/x64/SDL2.dll to your project folder next  to your cargo.toml.

as ref pls read https://github.com/Rust-SDL2/rust-sdl2 readme

**Comment by bugzmanov** [comment]
Thank you!. I've added a link and instruction that sdl2 dev lib needs to be installed as a per-requisite.
