### ISSUE TITLE
6502 Reference Link Invalid 

### ISSUE THREAD

**Issue by holmanb** [bugzmanov/nes_ebook#15]
The link on [this page](https://github.com/bugzmanov/nes_ebook/blob/master/src/chapter_3_1.md?plain=1) doesn't point to reference manual.

https://www.obelisk.me.uk/6502/reference.html

**Comment by holmanb** [comment]
Also a missing link to the instruction set manual on this page: https://github.com/bugzmanov/nes_ebook/blob/0f7f57390d5076941f3838182d0d476b859f8785/src/chapter_3_3.md?plain=1#L22

**Comment by Adam-Teng** [comment]
> The link on [this page](https://github.com/bugzmanov/nes_ebook/blob/master/src/chapter_3_1.md?plain=1&rgh-link-date=2022-04-23T18%3A49%3A32Z) doesn't point to reference manual.
> 
> [obelisk.me.uk/6502/reference.html](https://www.obelisk.me.uk/6502/reference.html)

You can refer [this](https://www.nesdev.org/obelisk-6502-guide/reference.html)

**Comment by bugzmanov** [comment]
thanks @holmanb and @Adam-Teng. fixed now!
