### ISSUE TITLE
Chapter 3.4 doesn't mention that you should change the load function

### ISSUE THREAD

**Issue by tralph3** [bugzmanov/nes_ebook#23]
I just got out of a 2 hour debugging session. After days of implementing processor instructions, I just wanted to see something run, but to my dismay, the SDL window opened and quickly closed, without showing anything. To discard any possible problems in my OS or libraries or whatever, I ran the version in this repo, and it worked.

After scratching my head for a while, I realized that the [load](https://github.com/bugzmanov/nes_ebook/blob/c9a57989ce7f56601549ed80f9f2c2c8a1cd48da/code/ch3.4/src/cpu.rs#L244) function quietly changed to load the contents of the program to another memory location. As you can see, in the [previous chapter](https://github.com/bugzmanov/nes_ebook/blob/c9a57989ce7f56601549ed80f9f2c2c8a1cd48da/code/ch3.3/src/cpu.rs#L236) it's different.

Please, state this clearly in the book. This program expects its code to be in a different memory location.

**Comment by bugzmanov** [comment]
hey @tralph3 . Sorry for causing you pain. And thank you for the feedback. I'll try to make it more clear

**Comment by tralph3** [comment]
No problem, thank you for the great work!

**Comment by pickles976** [comment]
Bump, issue has still not been fixed. Great tutorial though!

**Comment by bugzmanov** [comment]
@pickles976 thank you for reminding me about this. 

Living a hectic life of a new father and forget about everything 😪 
I've updated and put a note regarding new code location in memory. 

Thank you @tralph3 @pickles976

**Comment by pickles976** [comment]
Sorry for bugging you. Congrats on being a dad!
