### ISSUE TITLE
Chapter 3.4 regarding sdl2 possible error(Linux)

### ISSUE THREAD

**Issue by polpokpol** [bugzmanov/nes_ebook#28]
**_ld: library not found for -lSDL2_**

Open terminal and install:
Ubuntu: `sudo apt-get install libsdl2-dev` or Fedora: `sudo dnf install SDL2-devel` or Arch: `sudo pacman -S sdl2`

For more info: https://github.com/Rust-SDL2/rust-sdl2

**Comment by Josjfs** [comment]
Thanks, was looking for this. How bout windows?

**Comment by bugzmanov** [comment]
Have added a link and instruction that sdl2 dev lib needs to be installed as a per-requisite.

PS Damn.. this is a year old issue :)
