### ISSUE TITLE
Possibly a grammar mistake; Chapter 6.1

### ISSUE THREAD

**Issue by M-Phuykong** [bugzmanov/nes_ebook#32]
> [Emulating PPU memory access: Address and Data registers](https://bugzmanov.github.io/nes_ebook/chapter_6_1.html#emulating-ppu-memory-access-address-and-data-registers)
Let's try to emulate two the most complex registers: Address (0x2006) and Data(0x2007)

I believe it should be:

"Let's try to emulate two _of_ the most complex registers: Address (0x2006) and Data(0x2007)

**Comment by bugzmanov** [comment]
This is fixed. Thank you!
